/**
 * Domain enums. Previously generated by Prisma (`@prisma/client`); now declared
 * here so both the runtime values (e.g. `Role.ADMIN`) and the types (`role: Role`)
 * are available, and so `z.nativeEnum(...)` and Mongoose `enum:` validation work.
 */

export enum Role {
  CITIZEN = 'CITIZEN',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN',
}

export enum ReportStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  INFO_REQUESTED = 'INFO_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}

export enum MediaKind {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export enum AuditAction {
  REPORT_CREATED = 'REPORT_CREATED',
  REPORT_VIEWED = 'REPORT_VIEWED',
  EVIDENCE_VIEWED = 'EVIDENCE_VIEWED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  INFO_REQUESTED = 'INFO_REQUESTED',
  REPORT_APPROVED = 'REPORT_APPROVED',
  REPORT_REJECTED = 'REPORT_REJECTED',
  REPORT_CLOSED = 'REPORT_CLOSED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  DATA_EXPORTED = 'DATA_EXPORTED',
  DATA_ERASED = 'DATA_ERASED',
}

export enum AiAnalysisType {
  PLATE_OCR = 'PLATE_OCR',
  FACE_BLUR = 'FACE_BLUR',
  TAMPER_DETECTION = 'TAMPER_DETECTION',
  SUMMARY = 'SUMMARY',
}
